build_platform:
  linux_ppc64le: linux_64
  linux_aarch64: linux_64
  linux_loongarch64: linux_64
  linux_riscv64: linux_64
  osx_arm64: osx_64
  win_64: linux_64
conda_forge_output_validation: false
provider: {linux_aarch64: default, linux_loongarch64: default, linux_ppc64le: default, linux_riscv64: default}
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
remote_ci_setup:
  - conda-forge-ci-setup=4
  # https://github.com/conda/conda-build/issues/5613
  - conda-build <24.11
